version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata: null
